---
title: "Timings"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: lumen
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggtext)
library(patchwork)
library(tidyr)
library(here)
library(magick)

analysis_dir <- here("analysis")

source(file.path(analysis_dir, "knitr.R"))
source(file.path(analysis_dir, "theme.R"))
theme_set(theme_paper(base_size = 12))
```

```{r load_data, include=FALSE}
source(file.path(analysis_dir, "data.R"))
```

# Preliminaries

```{r prelim}
stage_cols <- c(
  "#77AADD", "#EE8866", "#EEDD88", "#FFAABB", "#99DDFF", "#44BB99"
)

metrics_new <- metrics_new %>%
  mutate(
    n_comp = as.factor(n_comp),
    n_hvg = as.factor(n_hvg),
    n_neig = as.factor(n_neig)
  )

timings_plot <- metrics_new %>%
  rename_with(~ sub("^timings_", "", .x), starts_with("timings_"))

timings_m <- metrics_new %>%
  pivot_longer(
    cols = starts_with("timings_"),
    names_to = "stage",
    values_to = "value"
  ) %>%
  mutate(
    stage = sub("^timings_", "", stage),
    method_cluster = as.factor(paste0(method, ".", d_cluster))
  )

table(timings_m$method_cluster)

timings_m_s <- timings_m %>%
  filter(
    filtering == "manual", n_comp == 20,
    n_neig == 15, n_hvg == 2000,
    stage %in% c(
      "gpu_load", "hvg", "normalization", "pca", "umap", "leiden"
    )
  )
table(timings_m_s$method_cluster)
```

# Timings figures

```{r timings, fig.height=3.5, fig.width=4}

timings_plot$gpu_load[is.na(timings_plot$gpu_load)] <- 0

timings_total <- timings_plot %>%
  filter(dataset == "cb") %>%
  group_by(method, n_comp, n_hvg) %>%
  summarise(
    total_time = median(gpu_load + hvg + pca + umap + leiden, na.rm = TRUE),
    .groups = "drop"
  )

panel_a <- ggplot(
    timings_plot %>% filter(dataset == "cb"),
    aes(x = method, y = gpu_load + hvg + pca + umap + leiden)
) +
    geom_boxplot(
        aes(group = method),
        width = 0.6, outlier.shape = NA,
        fill = "grey95", colour = "grey40"
    ) +
    geom_point(
        data = timings_total,
        aes(x = method, y = total_time, colour = n_comp, shape = n_hvg),
        position = position_jitter(width = 0.15, height = 0),
        size = 2
    ) +
    scale_color_pca() +
    scale_shape_manual(name = "HVGs", values = c(1, 4, 5)) +
    ylab("Total pipeline time <i>(s)</i>") +
    xlab("") +
    theme(
        axis.text.x = element_markdown(angle = 30, hjust = 1, vjust = 1.1),
        legend.position = "none"
    ) +
    scale_y_sqrt()
panel_a


timings_pca <- timings_plot %>%
  filter(dataset == "cb") %>%
  group_by(method, n_comp, n_hvg) %>%
  summarise(
    pca = median(pca, na.rm = TRUE),
    .groups = "drop"
  )

panel_b <- ggplot(
    timings_plot %>% filter(dataset == "cb"),
    aes(x = method, y = pca)
) +
    geom_boxplot(
        aes(group = method),
        width = 0.6, outlier.shape = NA,
        fill = "grey95", colour = "grey40"
    ) +
    geom_point(
        data = timings_pca,
        aes(x = method, y = pca, colour = n_comp, shape = n_hvg),
        position = position_jitter(width = 0.15, height = 0),
        size = 2
    ) +
    scale_color_pca() +
    scale_shape_manual(name = "HVGs", values = c(1, 4, 5)) +
    ylab("PCA time <i>(s)</i>") +
    xlab("") +
    theme(
        axis.text.x = element_markdown(angle = 30, hjust = 1, vjust = 1.1),
        legend.position = "bottom",
        legend.spacing.x = unit(0.2, "cm"),
        legend.margin = margin(t = 2, b = 2)
    ) +
    scale_y_sqrt()
panel_b

timings_umap <- timings_plot %>%
  filter(dataset == "cb") %>%
  group_by(method, n_comp) %>%
  summarise(
    umap = median(umap, na.rm = TRUE),
    .groups = "drop"
  )

panel_c <- ggplot(
    timings_plot %>% filter(dataset == "cb"),
    aes(x = method, y = umap)
) +
    geom_boxplot(
        aes(group = method),
        width = 0.6, outlier.shape = NA,
        fill = "grey95", colour = "grey40"
    ) +
    geom_point(
        data = timings_umap,
        aes(x = method, y = umap, colour = n_comp),
        position = position_jitter(width = 0.15, height = 0),
        size = 2, alpha = 0.75
    ) +
    scale_color_pca() +
    ylab("UMAP time <i>(s)</i>") +
    xlab("") +
    theme(
        axis.text.x = element_markdown(angle = 30, hjust = 1, vjust = 1.1),
        legend.position = "none"
    ) +
    scale_y_sqrt()
panel_c

panel_d <- ggplot(
  timings_m_s %>% filter(dataset == "cb"),
  aes(x = d_cluster, y = value, fill = stage)
) +
  geom_bar(position = "fill", stat = "identity") +
  facet_wrap(~method, scales = "free_x", nrow = 1) +
  scale_fill_manual(
    values = stage_cols,
    labels = function(x) {
      ifelse(
        x == "normalization", "norm.",
        ifelse(x == "gpu_load", "GPU load", x)
      )
    }
  ) +
  ylab("Proportion of time") +
  xlab("Delta number of clusters") +
  theme(
    legend.position = "bottom",
    legend.box = "vertical",
    legend.spacing.x = unit(0.2, "cm"),
    legend.margin = margin(t = 2, b = 2)
  ) +
  guides(fill=guide_legend(nrow=1))
panel_d
```

# Patchwork

```{r fig-timings, fig.height=8.85, fig.width=6.69}
png_image <- image_read(file.path(data_dir, "plan_alt2.png"))
png_plot <- image_ggplot(png_image)

wrap_elements(full = png_plot) / ((panel_a | panel_b | panel_c) / panel_d) +
  plot_layout(heights = c(1, 1.5)) +
  plot_annotation(tag_levels = "A")
```
