---
title: "ARI"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: lumen
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggtext)
library(here)
library(patchwork)

analysis_dir <- here("analysis")

source(file.path(analysis_dir, "knitr.R"))
source(file.path(analysis_dir, "theme.R"))
theme_set(theme_paper(base_size = 12))
```

```{r load_data, include=FALSE}
source(file.path(analysis_dir, "data.R"))
```

# ARI vs number of clusters

```{r ari-leiden-vs-clusters-group-paths, fig.height=5, fig.width=9}
ari_leiden_paths <- metrics_new %>%
  filter(filtering == "manual") %>%
  group_by(dataset, method, d_cluster) %>% # or n_clusters_leiden
  summarise(ari_median = median(agree_ari_leiden, na.rm = TRUE),
            ari_q25 = quantile(agree_ari_leiden, 0.25, na.rm = TRUE),
            ari_q75 = quantile(agree_ari_leiden, 0.75, na.rm = TRUE))

p_ari_leiden_paths <- ggplot(
  ari_leiden_paths, 
  aes(
    x = d_cluster, y = ari_median, # or n_clusters_leiden
    color = method, fill = method, group = method
  )
) +
  geom_ribbon(
    aes(ymin = ari_q25, ymax = ari_q75),
    alpha = 0.18, linewidth = 0,
    show.legend = FALSE
  ) +
  geom_line(linewidth = 0.8) +
  # geom_point(size = 1.5) + # optional
  facet_wrap(~dataset, scales = "free_x") +
  scale_color_method(name = "Method") +
  scale_fill_method(name = "Method") +
  labs(
    x = "Delta number of clusters", y = "ARI (Leiden)",
    color = "Method"
  )

p_ari_leiden_paths
```

# ARI v Timings

```{r leiden-ari-vs-total-timing, fig.height=4.5, fig.width=8}
timing_cols_keep <- paste0("timings_", c(
  "find_mit_gene", "filter", "normalization",
  "hvg", "scaling", "pca", "leiden"
))

ari_vs_total_timing <- metrics_new %>%
  filter(filtering == "manual") %>%
  mutate(total_seconds = rowSums(pick(all_of(timing_cols_keep)), na.rm = TRUE))

ari_vs_total_timing_top <- ari_vs_total_timing %>%
  group_by(dataset, method) %>%
  mutate(ari_p95 = quantile(agree_ari_leiden, probs = 0.95)) %>%
  filter(agree_ari_leiden >= ari_p95) %>%
  ungroup() %>%
  select(-ari_p95)

set.seed(42)
s <- sample(nrow(ari_vs_total_timing_top))

p_ari_vs_total_timing <- ggplot(
  ari_vs_total_timing_top[s, ],
  aes(x = total_seconds, y = agree_ari_leiden, color = method)
) +
  geom_point(
    data = ari_vs_total_timing,
    alpha = 0.75, size = 1.4, colour = "grey95"
  ) +
  geom_point(alpha = 0.8, size = 1.6) +
  facet_wrap(~dataset, scales = "free_x") +
  scale_color_method(name = "Method") +
  scale_x_log10() +
  labs(x = "Total timing <i>(s)</i>", y = "ARI (Leiden)", color = "Method")

p_ari_vs_total_timing
```

# Compare with Billato et al.

```{r compare-billato}
billato_long <- billato %>%
  pivot_longer(
    cols = c(agree_ari_leiden, agree_ari_louvain),
    names_to = "best_for", values_to = "billato_ari"
  ) %>%
  mutate(
    best_for = recode(
      best_for,
      agree_ari_leiden = "leiden", agree_ari_louvain = "louvain"
    )
  )

p_ari <- metrics_new %>%
  group_by(dataset, method) %>%
  summarize(
    leiden.95 = quantile(agree_ari_leiden, probs = 0.95, na.rm = TRUE),
    louvain.95 = quantile(agree_ari_louvain, probs = 0.95, na.rm = TRUE),
    leiden.05 = quantile(agree_ari_leiden, probs = 0.05, na.rm = TRUE),
    louvain.05 = quantile(agree_ari_louvain, probs = 0.05, na.rm = TRUE),
    leiden.50 = quantile(agree_ari_leiden, probs = 0.5, na.rm = TRUE),
    louvain.50 = quantile(agree_ari_louvain, probs = 0.5, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_longer(
    cols = c(leiden.05, louvain.05, leiden.50, louvain.50, leiden.95, louvain.95),
    names_to = "clustering", values_to = "our_ari"
  ) %>%
  mutate(group = paste0(dataset,"_",method,"_",clustering)) %>%
  mutate(best_for = gsub(".[0-9][0-9]$","", clustering))

compare_ari <- p_ari %>%
  left_join(billato_long, by = c("dataset", "method", "best_for")) %>%
  mutate(
    method = factor(method, levels = names(met_cols)),
    best_for = factor(as.character(best_for), levels = c("leiden", "louvain")),
    dataset = factor(dataset, levels = names(dataset_cols))
  ) %>%
  arrange(method, dataset, best_for) 

compare_ari
```

```{r plot-billato, fig.height=4.5, fig.width=5}
ari_limits_p95 <- range(
  c(compare_ari$billato_ari, compare_ari$our_ari),
  na.rm = TRUE
)

p_billato <- ggplot(compare_ari %>% filter(best_for=="louvain"), aes(
  x = billato_ari, y = our_ari,
  fill = method, size = best_for, shape = dataset
  )) +
    geom_line(alpha = .9, colour="grey85", linewidth = .5) +
    geom_abline(slope = 1, intercept = 0, 
                linetype = "dashed", color = "grey50") +
    geom_point(alpha = 0.65, color = "black") +
    labs(x = "<i>Billato et al.</i> ARI",
         y = "Our 5/50/95<sup>th</sup> %tile ARI",
         fill = "Method"
    ) +
    #coord_equal(xlim = ari_limits_p95, ylim = ari_limits_p95) +
    scale_fill_method(name = "Method") +
    scale_shape_manual(name = "Dataset", values = c(21, 22, 24, 25)) +
    scale_size_manual(name = "Algorithm", values = c(leiden = 3.5, louvain = 2)) +
    guides(
        fill = guide_legend(override.aes = list(shape = 21, size = 4)),
        shape = guide_legend(override.aes = list(size = 4, fill = "grey80")),
        size = guide_legend(override.aes = list(shape = 21, fill = "grey80"))
    )

p_billato
```

# Patchwork

```{r fig-ari, fig.height=7.6, fig.width=6.69}
layout_main <- "
AA
BB
CD
"

p_main_panels <- (
  (p_ari_leiden_paths + guides(color = "none")) +
    (p_ari_vs_total_timing + guides(color = "none")) +
    p_billato +
    guide_area()
) +
  plot_layout(
    design = layout_main,
    heights = c(1.25, 1.25, 1.0),
    guides = "collect"
  ) +
  plot_annotation(tag_levels = "A") &
  theme(
    legend.position = "left",
    legend.box = "horizontal",
    legend.direction = "vertical"
  )

p_main_panels
```


# Patchwork

```{r playing-around-extra-panel}
agree_cols <- grep("agree", colnames(metrics_new))
struc_cols <- grep("struc", colnames(metrics_new))
library(pheatmap)
pheatmap(cor(metrics_new[,c(agree_cols, struc_cols)]))

ggplot(metrics_new, 
       aes(x = struc_davies_bouldin_louvain, 
           y = agree_ari_louvain,
           colour = method, shape = dataset)) +
  scale_colour_manual(values = met_cols) +
  geom_point()

ggplot(metrics_new, 
       aes(x = struc_silhouette_louvain, 
           y = agree_ari_louvain,
           colour = method, shape = dataset)) +
  scale_colour_manual(values = met_cols) +
  geom_point()

ggplot(metrics_new, 
       aes(x = agree_ari_louvain, 
           y = agree_ari_leiden,
           colour = method, shape = dataset)) +
  scale_colour_manual(values = met_cols) +
  geom_point()

```

