---
title: "Supplementary: Timings"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: lumen
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggtext)
library(patchwork)
library(tidyr)
library(here)

analysis_dir <- here("analysis")

source(file.path(analysis_dir, "knitr.R"))
source(file.path(analysis_dir, "theme.R"))
theme_set(theme_paper(base_size = 12))
```

```{r load_data, include=FALSE}
source(file.path(analysis_dir, "data.R"))
```

# Preliminaries

```{r prelim}
metrics_new <- metrics_new %>%
  mutate(
    n_comp = as.factor(n_comp),
    n_hvg = as.factor(n_hvg),
    n_neig = as.factor(n_neig)
  )

timings_plot <- metrics_new %>%
  rename_with(~ sub("^timings_", "", .x), starts_with("timings_"))
```

# Timings figures

```{r timings-supp, fig.height=3.5, fig.width=8}
p_pca <- ggplot(
  timings_plot, aes(method, pca, colour = n_comp, shape = n_hvg)
) +
  geom_point(
    position = position_jitterdodge(
      dodge.width = 1, jitter.width = .2
    ), size = .6
  ) +
  facet_wrap(~dataset, scales = "free") +
  scale_color_pca() +
  scale_shape_manual(name = "HVGs", values = c(1, 3, 5)) +
  ylab("PCA time <i>(s)</i>") +
  theme(
    axis.text.x = element_markdown(angle = 30, hjust = 1, vjust = 1.1)
  ) +
  scale_y_log10()
p_pca

p_leiden <- ggplot(
  timings_plot, aes(method, leiden, colour = n_neig)
) +
  geom_point(
    position = position_jitterdodge(
      dodge.width = 0.9, jitter.width = .25
    ), size = .6
  ) +
  facet_wrap(~dataset, scales = "free") +
  scale_color_n_neig() +
  ylab("Leiden time <i>(s)</i>") +
  theme(
    axis.text.x = element_markdown(angle = 30, hjust = 1, vjust = 1.1)
  ) +
  scale_y_log10()
p_leiden

p_umap <- ggplot(
  timings_plot, aes(method, umap, colour = n_comp)
) +
  geom_point(
    position = position_jitterdodge(
      dodge.width = 0.8, jitter.width = .35
    ), size = .6
  ) +
  facet_wrap(~dataset, scales = "free") +
  scale_color_pca() +
  ylab("Umap time <i>(s)</i>") +
  theme(
    axis.text.x = element_markdown(angle = 30, hjust = 1, vjust = 1.1)
  ) +
  scale_y_log10()
p_umap
```

# Patchwork

```{r supp5, fig.height=8.85, fig.width=6.69}
(p_pca / p_umap / p_leiden) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") & theme(
  legend.position = "bottom", legend.box = "vertical", legend.box.just = "left",
  legend.margin = margin_part(t = -8)
)
```
